"""Markdown reporter for dependency audit results."""
from dataclasses import dataclass
from typing import List, Optional
from src.detectors.base import DetectionResult


@dataclass
class MarkdownReporter:
    """Generates a Markdown summary report from detection results."""

    title: str = "🔍 Dependency Audit Report"
    show_up_to_date: bool = False

    def render(self, results: List[DetectionResult]) -> str:
        """Render a full Markdown report from a list of DetectionResults."""
        lines: List[str] = []
        lines.append(f"# {self.title}\n")

        outdated_total = sum(
            1 for r in results for d in r.dependencies if d.outdated
        )
        total = sum(len(r.dependencies) for r in results)

        lines.append(
            f"> Scanned **{total}** dependencies across **{len(results)}** manifest(s). "
            f"Found **{outdated_total}** outdated.\n"
        )

        if not results:
            lines.append("_No dependency files detected._\n")
            return "\n".join(lines)

        for result in results:
            lines.append(self._render_result(result))

        lines.append("---")
        lines.append("_Generated by [depcheck-action](https://github.com/depcheck-action)_")
        return "\n".join(lines)

    def _render_result(self, result: DetectionResult) -> str:
        """Render a single DetectionResult as a Markdown section."""
        lines: List[str] = []
        lines.append(f"## 📦 `{result.manifest_path}` ({result.ecosystem})\n")

        outdated = [d for d in result.dependencies if d.outdated]
        up_to_date = [d for d in result.dependencies if not d.outdated]

        if outdated:
            lines.append("### ⚠️ Outdated Dependencies\n")
            lines.append("| Package | Current | Latest |")
            lines.append("|---------|---------|--------|")
            for dep in sorted(outdated, key=lambda d: d.name):
                latest = dep.latest_version or "_unknown_"
                lines.append(f"| `{dep.name}` | `{dep.current_version}` | `{latest}` |")
            lines.append("")
        else:
            lines.append("✅ All dependencies are up to date.\n")

        if self.show_up_to_date and up_to_date:
            lines.append("<details><summary>Up-to-date dependencies</summary>\n")
            lines.append("| Package | Version |")
            lines.append("|---------|---------|")
            for dep in sorted(up_to_date, key=lambda d: d.name):
                lines.append(f"| `{dep.name}` | `{dep.current_version}` |")
            lines.append("</details>\n")

        return "\n".join(lines)
